### ISSUE TITLE
Error in drilldown.py

### ISSUE THREAD

**Issue by AkshDesai04** [AkshDesai04/PyCompare#17]
Error read:
Traceback (most recent call last):
  File ".\main.py", line 1, in <module>
    import drilldown
  File "C:\Users\akshd\PycharmProjects\PyCompare\drilldown.py", line 3, in <module>
    def drilldown(targeted_directory:str, extensions:list[str] = ['.bmp', '.dib', '.jpeg', '.jpg', '.jp2', '.png', '.pbm', '.pgm', '.ppm', '.sr', '.ras', '.tiff', '.tif', '.exr', '.jxr', '.pfm', '.pds', '.pfm', '.viff', '.xbm', '.xpm', '.dds', '.eis', '.mng', '.web', '.hei', '.hei', '.av']):
TypeError: 'type' object is not subscriptable

@poneoneo

**Comment by AkshDesai04** [comment]
Please pull before trying to recreate. This was after a few merges' and other commits.
